[package]
name = "parted-information-extractor-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
byte-unit = "5.1.4"
duct = "0.13.7"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
users = "0.11.0"
