[package]
name = "tea-partition-api-lib"
<<<<<<< HEAD
version = "0.2.2"
=======
version = "0.2.3"
>>>>>>> main
edition = "2021"

[dependencies]
byte-unit = "5.1.4"
duct = "0.13.7"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
users = "0.11.0"
